viper.o: viper.c vp_state.h vp_buf.h vp_def.h vp_ir.h vp_str.h vp_mem.h \
  vp_regalloc.h vp_type.h vp_tab.h vp_map.h
vp_asm.o: vp_asm.c vp_asm.h vp_state.h vp_buf.h vp_def.h vp_ir.h vp_str.h \
  vp_mem.h vp_regalloc.h vp_type.h vp_tab.h vp_map.h
vp_assert.o: vp_assert.c vp_def.h
vp_ast.o: vp_ast.c vp_ast.h vp_lex.h vp_buf.h vp_def.h vp_state.h vp_ir.h \
  vp_str.h vp_mem.h vp_regalloc.h vp_type.h vp_tab.h vp_map.h vp_var.h
vp_buf.o: vp_buf.c vp_buf.h vp_def.h vp_mem.h
vp_char.o: vp_char.c vp_char.h vp_def.h
vp_codegen.o: vp_codegen.c vp_codegen.h vp_ast.h vp_lex.h vp_buf.h \
  vp_def.h vp_state.h vp_ir.h vp_str.h vp_mem.h vp_regalloc.h vp_type.h \
  vp_tab.h vp_map.h vp_var.h vp_vec.h vp_dump.h
vp_dump.o: vp_dump.c vp_dump.h vp_ast.h vp_lex.h vp_buf.h vp_def.h \
  vp_state.h vp_ir.h vp_str.h vp_mem.h vp_regalloc.h vp_type.h vp_tab.h \
  vp_map.h vp_var.h vp_vec.h vp_sema.h
vp_err.o: vp_err.c vp_err.h vp_lex.h vp_buf.h vp_def.h vp_state.h vp_ir.h \
  vp_str.h vp_mem.h vp_regalloc.h vp_type.h vp_tab.h vp_map.h
vp_ir.o: vp_ir.c vp_ir.h vp_str.h vp_def.h vp_mem.h vp_state.h vp_buf.h \
  vp_regalloc.h vp_type.h vp_tab.h vp_map.h vp_vec.h
vp_lex.o: vp_lex.c vp_lex.h vp_buf.h vp_def.h vp_state.h vp_ir.h vp_str.h \
  vp_mem.h vp_regalloc.h vp_type.h vp_tab.h vp_map.h vp_char.h vp_err.h \
  vp_strscan.h
vp_load.o: vp_load.c vp_lex.h vp_buf.h vp_def.h vp_state.h vp_ir.h \
  vp_str.h vp_mem.h vp_regalloc.h vp_type.h vp_tab.h vp_map.h vp_parse.h \
  vp_ast.h vp_var.h vp_sema.h vp_codegen.h
vp_map.o: vp_map.c vp_map.h vp_def.h vp_mem.h
vp_mem.o: vp_mem.c vp_mem.h vp_vec.h vp_def.h
vp_parse.o: vp_parse.c vp_parse.h vp_ast.h vp_lex.h vp_buf.h vp_def.h \
  vp_state.h vp_ir.h vp_str.h vp_mem.h vp_regalloc.h vp_type.h vp_tab.h \
  vp_map.h vp_var.h vp_err.h vp_vec.h
vp_pe.o: vp_pe.c vp_buf.h vp_def.h vp_emit.h vp_state.h vp_ir.h vp_str.h \
  vp_mem.h vp_regalloc.h vp_type.h vp_tab.h vp_map.h
vp_regalloc.o: vp_regalloc.c vp_regalloc.h vp_ir.h vp_str.h vp_def.h \
  vp_type.h vp_mem.h vp_state.h vp_buf.h vp_tab.h vp_map.h vp_vec.h
vp_sema.o: vp_sema.c vp_sema.h vp_ast.h vp_lex.h vp_buf.h vp_def.h \
  vp_state.h vp_ir.h vp_str.h vp_mem.h vp_regalloc.h vp_type.h vp_tab.h \
  vp_map.h vp_var.h vp_err.h vp_vec.h vp_dump.h
vp_state.o: vp_state.c vp_state.h vp_buf.h vp_def.h vp_ir.h vp_str.h \
  vp_mem.h vp_regalloc.h vp_type.h vp_tab.h vp_map.h vp_lex.h vp_var.h
vp_str.o: vp_str.c vp_str.h vp_def.h vp_mem.h vp_tab.h vp_state.h \
  vp_buf.h vp_ir.h vp_regalloc.h vp_type.h vp_map.h
vp_strscan.o: vp_strscan.c vp_char.h vp_def.h vp_lex.h vp_buf.h \
  vp_state.h vp_ir.h vp_str.h vp_mem.h vp_regalloc.h vp_type.h vp_tab.h \
  vp_map.h vp_strscan.h
vp_tab.o: vp_tab.c vp_tab.h vp_str.h vp_def.h vp_mem.h
vp_type.o: vp_type.c vp_type.h vp_str.h vp_def.h vp_map.h vp_mem.h \
  vp_vec.h vp_state.h vp_buf.h vp_ir.h vp_regalloc.h vp_tab.h
vp_var.o: vp_var.c vp_var.h vp_ir.h vp_str.h vp_def.h vp_state.h vp_buf.h \
  vp_mem.h vp_regalloc.h vp_type.h vp_tab.h vp_map.h vp_vec.h
vp_vec.o: vp_vec.c vp_vec.h vp_def.h vp_mem.h
